### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AMDmi3** [OpenRCT2/title-sequences#3]
License is not defined for this project. What is it? Is the data safe to include to OpenRCT2 package?

**Comment by Gymnasiast** [comment]
Since it has been created by the same people doing the OpenRCT2 project and contains stuff that used to be directly in OpenRCT2 itself, it is safe to include.

But we forgot to explicitly mention a licence indeed. We'll fix that.

**Comment by AMDmi3** [comment]
Thank you!

**Comment by IntelOrca** [comment]
I expect it will be CC or similar.

https://github.com/PFCKrutonium/OpenRCT2-OpenScenarios agreed on CC-BY-SA-4.0, so maybe that.

**Comment by Gymnasiast** [comment]
@IntelOrca As free as possible, AFAIC. It's just metadata, after all.

Regardless of what we pick, @spacek531 has to agree. Otherwise it will default to GPL-3.0, as it was originally taken from the regular repository, which is under GPL-3.0.

I think that @spacek531 and you just have to agree on a licence, as the sole copyright holders of the current title sequences. I'm not going to be too pushy on a specific licence.

**Comment by spacek531** [comment]
I'm down for whatever.

**Comment by gibmat** [comment]
Pinging this, as I'm working on Debian packaging and need license information to be defined for this repo. Especially for the .sv6's in the custom title sequences, clear licensing information is needed. Either from the original authors, or a pointer to where submitters agreed to some licensing (public domain, some OSS license, etc).

**Comment by Gymnasiast** [comment]
I propose picking CC-0. It releases the contents of the repository into the public domain. The reason for this is that's it's mostly metadata (the RCT1/2 title sequences), plus the official ones. CC-0 keeps the licence terms simple: do whatever you like with it.

An alternative would be CC-BY, which requires attribution, but has otherwise no strings attached.

Since @spacek531 @IntelOrca and I are the only ones to have significantly contributed to this repo, I'd like to get an ack from both, and then I'll create the appropriate licence file.

**Comment by spacek531** [comment]
I'm fine with whatever license for my works, but my works include parks created by other people. These people gave me written permission to include their parks in official OpenRCT2 title sequences, but no specific license was requested of them. The ability for OpenRCT2 to modify and distribute their works was implied with the agreement they made with me, but no specific terms.

**Comment by Gymnasiast** [comment]
We discussed this tonight in the team meeting and ultimately decided on CC-BY. That means that others cannot just pass off the parks as their own.
