### ISSUE TITLE
[RFC] 0.1.2 title sequence

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/title-sequences#4]
I was asked to produce a new title sequence for 0.1.2. I have a little more time to produce it than the last one, so I hope it turns out better for it. I have made this issue for your comments on its progress.

This sequence I would say is half to three-quarters finished:

- It needs more content to bring it up to two music loops in length
- Remove SpacekShrews and SpacekKing if possible, since they have already appeared in title sequences
- Use only one version of Yokum Creek, since it has the largest file size of all the included parks

[Download the sequence by clicking this link](https://github.com/OpenRCT2/title-sequences/files/1629301/012.sequence.RFC.2.zip) [EDIT: updated to version 2] and unzip it into your `OpenRCT2/title sequences` folder. Play the sequence by opening a scenario or park, then open the options menu and select the sequence in the 'ride' tab. Once it is selected, quit to the main menu to view the title sequence with synchronized music.

What are your thoughts on this title sequence? Better or worse than the 0.1.0 sequence? Better or worse than the 0.0.5 sequence? Do you think changing the order of some parks will improve it? Have a park that works as a title sequence park? Let me know below.

**Comment by janisozaur** [comment]
FYI: There's no need package a ZIP archive into a ZIP archive.

**Comment by spacek531** [comment]
.parkseq is not an approved Github extension, so it is necessary to have the outer file with said extension. Compoinding this is OpenRCT2 does not recognize .zip as title sequence file, only .parkseq. So for the ease of everyone involved, I zipped the parkseq file.

**Comment by janisozaur** [comment]
Here's a lifehack for you: modern OSs have this amazing feature that allow you to _rename_ files.

**Comment by spacek531** [comment]
And as wonderful as modern OSs are, I don't feel like explaining to everyone every other comment that they need to do that, especially if their computer does not display extensions.

**Comment by janisozaur** [comment]
In the first park of this title sequence there is some very noticeable and distracting flicker, at least on my end. It can be observed with both, OpenGL and Software + HW display renderers. I'm not sure where the issue lies or how does vanilla handle that, but I've seen it in some other parks as well (most notably the "dome" park: https://github.com/OpenRCT2/OpenRCT2/files/462687/dome-roof-on_zoom1.sv6.zip)

**Comment by AaronVanGeffen** [comment]
Cheers for taking the time to make yet another sequence! I think it's looking very nice so far, and I love that you're showing new features like the railway crossings, too.

One possible gripe would be that, while it looks amazing, the first park takes a little more time to load and render than the others, because it contains so many objects. Well, on my laptop, at least — which hasn't got as much of an issue with the current title sequence, anyway.

Perhaps you could show off the new 'follow sprite' feature for a train on the red roller coaster? The park seems to be relatively light to render, anyway. (Its position in the sequence is fine as-is!)

**Comment by callmeDJ169** [comment]
I have no problems playing the title sequence, but my computer is relatively powerful compared to others (16 GB of RAM and a eight-core processor). The Bayou was a fantastic choice for your title sequence, and Velocita di Volo is one of the best launched coasters I've ever seen!

**Comment by deurklink** [comment]
New title sequence is very promising! I like that there are some merged rides, which show some of the stuff that's possible with OpenRCT2. Like janizosaur, I was a little bit bothered by the flickering.

**Comment by spacek531** [comment]
@AaronVanGeffen I haven't had any issues loading the first park. It's one of the medium-sized parks at ~700 kb.

I decided not to use Follow Sprite in the title sequence because of tearing and poor framerate. My goal is to support 1080p screens, and Follow Sprite is too much for my mid-end computer to handle.

**Comment by Xardoz** [comment]
I have some things who are.. flickering ? (some little parts of elements who disappear/reappear)
I'm in fullscreen, in software mode. I made you two screenshot of the first two screens in case it could help (I can edit my comment and remove them if they're useless).
![flickering0](https://user-images.githubusercontent.com/35117010/34901580-f635bd0e-f803-11e7-9ce0-82ff7bdf456b.png)
![flickering1](https://user-images.githubusercontent.com/35117010/34901581-f6586b24-f803-11e7-8574-02fa7c577f30.png)

Thanks for your work by the way :)

**Comment by gbarks** [comment]
Love this title sequence! It's really amazing to see how your knack for finding that classic "flow" has improved over the course of OpenRCT2's development.

I love the choice for The Bayou as the opening park, though I wasn't experiencing any of the flickering other users reported (thanks @Xardoz for posting where to look).

Just about my only complaint is that some scenes are unnecessarily short. Starting with the Arrow hypercoaster, there's three shots when the first and second can probably be merged, and then the flying coaster cuts to a second shot when just one long one would have done. Ditto for the shot of the launched looper from the last title sequence (though the red B&M doesn't have this issue, since it feels like there's more new information in the second shot). Just some minor ideas - I also haven't watched with music yet since I'm at work.

**Comment by IntelOrca** [comment]
@spacek531 I think there is an absence of quiet moments in the sequence. Some previous sequence moments I liked were:

* Train going through the factory in snow / ice landscape.
* Guests walking around a garden.

Both moments have no noise from crowd or coasters. It is nice to have in between busy shots.

**Comment by spacek531** [comment]
Thanks for the feedback everyone. Good point about the quiet moments, that's something I think I forgot in the last sequence. The parks I have for this sequence are almost exclusively high thrill ones so it's not exactly the low-energy shots in the 0.0.5 and 0.0.4 sequences. The shot with the scrambler and ferris wheel and the shot with the tram are hopefully low-energy enough to fill that niche.

Below is RFC version 2. I've made a number of changes to the order of parks that I think is for the better.

[012 sequence RFC 2.zip](https://github.com/OpenRCT2/title-sequences/files/1629301/012.sequence.RFC.2.zip)

What do you all think of this new version?

**Comment by Xardoz** [comment]
@gbarks : No problem, I really didn't knew if it would be useful, I'm glad if it can helps :)
@spacek531 : I agree with other for the gentle ride missing. And I would even add (a bit like @IntelOrca  )... "quiet" scenery/landscape ? like colorful trees, haunted hill... things like that ? Simply suggesting, and these are examples of course :)
I'm liking it so far, good job, keep up this way ;)
(oh, and I still have the flickering issue)

**Comment by spacek531** [comment]
I attempted to include a scene of some swan boats using Faas's Lucky Lake Amusement Park to replace the scene with the twist ride and the ferris wheel to create a better lull in the action, but I couldn't feel any improvement over the RFC v2 sequence except bloating overall size by a megabyte.

Since there's nothing more anyone wants to say about the sequence, I am going to be submitting the RFC version 2 as the final version with some optimizations to improve park loading times via object selection.

**Comment by spacek531** [comment]
I am rather pleased with the optimizations I have done for this title sequence. By far the largest expense when switching parks is unloading unused objects and loading new objects. I spent several hours today synchronizing the object selections of all the parks to within 2 objects of each other, and that hard work has paid off: transitions are snappier than ever, enough so that I have to edit the script so the shots last for longer: the title sequence has shortened by half a second from its original 208 second length.

**Comment by IntelOrca** [comment]
@spacek531 There is always room for improvement on the code end. One thing I would like to do at some point is pre-load the objects for the next park in the sequence on a background thread.

**Comment by spacek531** [comment]
The title sequence has been optimized and re-synchronized with the music. I am pleased with the sequence and I think it gives the 0.0.5 sequence a run for its money. I want to add credits to the sequence via text while the sequence plays, but if the PR falls through on implementing that, the sequence currenty in pr #6 is what the 0.1.2 sequence will look like.
